# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1


    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'


    - name: do autosidebar
      run: |
       node ./auto.js
       ls
       
    - name: Commit Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Auto commit by GitHub Actions"
        git push
      working-directory: ./
